export interface Ginfes {
    id: number,
    diacompetencia: string,
    datahoraemissao: Date,
    datavalidade: Date,
    cstat: string,
    codigocontrolecertidao: string,
    observacao: string,
    tempo: number,
    arquivo: Text,
    obrigacao: string,
    filetype: string,
    instance_name: string,
    token: string,
    synched: boolean,
    cnpj: string,
    usuario_ginfes: string,
    senha_ginfes: string,
    cod_ibge_mun: string,
    sys_ident: string
}
