export interface Giss {
    id: number,
    competencia: string,
    datahoraemissao: Date,
    datavalidade: Date,
    cstat: string,
    codigocontrolecertidao: string,
    observacao: string,
    tempo: number,
    arquivo: string,
    obrigacao: string,
    filetype: string,
    instance_name: string,
    user_giss: string,
    senha_giss: string,
    cnpj: string,
    arquivo_tomados: string,
    token: string,
    synched: boolean,
    sys_ident: string,
    datahorarequisicao: Date,
    livro_tomados: string,
    guia_prestados: string,
    guia_tomados: string,
    rel_notas_emit: string,
    livro_prestados: string,
    cod_ibge_mun: string
}