export interface Giss {
    id: number,
    diacompetencia: string,
    datahoraemissao: Date,
    datavalidade: Date, 
    cstat: string, 
    codigocontrolecertidao: string, 
    observacao: string, 
    tempo: number, 
    arquivo: string, 
    obrigacao: string, 
    filetype: string, 
    instance_name: string, 
    token: string, 
    synched: boolean, 
    cnpj: string, 
    usuario_ginfes: string, 
    senha_ginfes: string, 
    cod_ibge_mun: string, 
    sys_ident: string
}